[package]
name = "sr71-ctl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
sr71-core = { path = "../sr71-core" }
rmp-serde = {workspace = true }
tokio = { workspace = true, features = ["full"] }
anyhow = "1"
